import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy Policy for Meghna Power. Learn how we collect, use, and protect your personal information when you contact us or use our website.",
  alternates: { canonical: "https://meghnapower.biz/privacy-policy" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "30 May 2025";
const COMPANY = "Meghna Power";
const ADDRESS = "Chowala, Narsingdi, Bangladesh";
const EMAIL = "info@meghnapower.biz";
const PHONE = "+880 1741 774141";
const SITE = "https://meghnapower.biz";

export default function PrivacyPolicy() {
  return (
    <div style={{ background: "#050505", minHeight: "100vh", color: "rgba(255,255,255,0.8)", fontFamily: "var(--font-inter), sans-serif" }}>

      {/* Nav bar strip */}
      <header style={{ borderBottom: "1px solid rgba(249,115,22,0.15)", padding: "1.25rem 1.5rem", display: "flex", alignItems: "center", gap: "1rem" }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: "0.75rem", textDecoration: "none" }}>
          <Image src="/logo.png" alt="Meghna Power" width={36} height={36} style={{ objectFit: "contain" }} />
          <span style={{ fontFamily: "var(--font-barlow), sans-serif", fontSize: "1.1rem", fontWeight: 800, color: "#fff", letterSpacing: "-0.02em" }}>
            MEGHNA <span style={{ color: "#f97316" }}>POWER</span>
          </span>
        </Link>
        <span style={{ marginLeft: "auto", fontSize: "0.8rem", color: "rgba(255,255,255,0.3)" }}>
          <Link href="/" style={{ color: "rgba(255,255,255,0.4)", textDecoration: "none" }}>Home</Link>
          {" / "}Privacy Policy
        </span>
      </header>

      <main style={{ maxWidth: "760px", margin: "0 auto", padding: "4rem 1.5rem 6rem" }}>

        {/* Title */}
        <div style={{ marginBottom: "3rem" }}>
          <div style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.15em", textTransform: "uppercase", color: "#f97316", marginBottom: "0.75rem" }}>
            Legal
          </div>
          <h1 style={{ fontFamily: "var(--font-barlow), sans-serif", fontSize: "clamp(2rem, 5vw, 3rem)", fontWeight: 800, color: "#fff", letterSpacing: "-0.03em", lineHeight: 1.1, marginBottom: "0.75rem" }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: "0.875rem", color: "rgba(255,255,255,0.3)" }}>
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "2.5rem" }}>

          <Section title="1. Who We Are">
            <p>
              <strong style={{ color: "#fff" }}>{COMPANY}</strong> is an electrical equipment manufacturer based at {ADDRESS}.
              We manufacture and supply transformers, CT-PT units, Auto PFI panels, LT/HT switchgear, industrial exhaust fans, and solar systems.
            </p>
            <p>This policy explains what personal information we collect when you visit <a href={SITE} style={linkStyle}>{SITE}</a> or submit our contact form, and how we use it.</p>
          </Section>

          <Section title="2. Information We Collect">
            <p>We collect personal information <strong style={{ color: "#fff" }}>only when you voluntarily submit our contact / quote request form</strong>. The fields collected are:</p>
            <ul style={listStyle}>
              <li>Full name</li>
              <li>Phone number / WhatsApp number</li>
              <li>Email address</li>
              <li>Product or service of interest</li>
              <li>Project location</li>
              <li>Any additional message you choose to include</li>
            </ul>
            <p>We do not collect any information passively beyond standard server logs (IP address, browser type, referring URL) that are automatically generated by web servers.</p>
          </Section>

          <Section title="3. How We Use Your Information">
            <p>Information submitted through the contact form is used exclusively to:</p>
            <ul style={listStyle}>
              <li>Respond to your enquiry or quote request</li>
              <li>Provide technical information about our products</li>
              <li>Follow up on project requirements if you have given us explicit permission to do so</li>
            </ul>
            <p>We do <strong style={{ color: "#fff" }}>not</strong> use your information for automated marketing, profiling, or any purpose unrelated to your enquiry.</p>
          </Section>

          <Section title="4. No Third-Party Sharing">
            <p>
              We do <strong style={{ color: "#fff" }}>not sell, rent, trade, or otherwise share</strong> your personal information with any third party, advertiser, or data broker.
            </p>
            <p>
              Your form submissions are received and processed solely by {COMPANY} staff. We use <strong style={{ color: "#fff" }}>Resend</strong> as our email delivery provider to route form notifications to our inbox — your data passes through their servers in transit but is not stored or used by them for any other purpose. Resend is GDPR-compliant.
            </p>
            <p>
              We may disclose information only if required by applicable law or a valid legal process.
            </p>
          </Section>

          <Section title="5. Cookies">
            <p>Our website uses a minimal set of cookies:</p>
            <table style={tableStyle}>
              <thead>
                <tr>
                  <th style={thStyle}>Cookie / Technology</th>
                  <th style={thStyle}>Purpose</th>
                  <th style={thStyle}>Retention</th>
                </tr>
              </thead>
              <tbody>
                <CookieRow
                  name="Language preference"
                  purpose="Remembers your selected site language (English / Bengali). Set locally in your browser."
                  retention="Session / localStorage"
                />
                <CookieRow
                  name="Facebook Pixel (optional)"
                  purpose="Anonymous aggregate analytics for advertising reach measurement, loaded only when FB_PIXEL_ID is configured. No personally identifiable data is linked."
                  retention="90 days (Facebook-managed)"
                />
              </tbody>
            </table>
            <p>We do not use tracking cookies for remarketing or behavioural profiling. You can disable cookies in your browser settings at any time without affecting core site functionality.</p>
          </Section>

          <Section title="6. Data Retention">
            <p>
              Enquiry emails are retained in our inbox for as long as necessary to complete the business relationship, and deleted when no longer needed. We do not maintain a separate database of contact form submissions.
            </p>
          </Section>

          <Section title="7. Your Rights">
            <p>You may contact us at any time to:</p>
            <ul style={listStyle}>
              <li>Request a copy of the information we hold about you</li>
              <li>Ask us to correct inaccurate information</li>
              <li>Ask us to delete your information</li>
            </ul>
            <p>We will respond within 7 business days.</p>
          </Section>

          <Section title="8. Data Security">
            <p>
              Our website is served over HTTPS. Form submissions are transmitted over encrypted connections. We apply reasonable technical and organisational measures to protect your data, though no internet transmission is 100% secure.
            </p>
          </Section>

          <Section title="9. Children's Privacy">
            <p>
              Our services are directed at businesses and professionals. We do not knowingly collect information from anyone under 18 years of age.
            </p>
          </Section>

          <Section title="10. Changes to This Policy">
            <p>
              We may update this policy from time to time. The "Last updated" date at the top of this page will reflect any changes. Continued use of the site after changes constitutes acceptance of the revised policy.
            </p>
          </Section>

          <Section title="11. Contact Us">
            <p>For any privacy-related questions or requests:</p>
            <div style={{ marginTop: "1rem", padding: "1.25rem 1.5rem", background: "rgba(249,115,22,0.06)", border: "1px solid rgba(249,115,22,0.15)", borderRadius: "8px", display: "flex", flexDirection: "column", gap: "0.5rem" }}>
              <span style={{ fontWeight: 700, color: "#fff" }}>{COMPANY}</span>
              <span>{ADDRESS}</span>
              <a href={`mailto:${EMAIL}`} style={linkStyle}>{EMAIL}</a>
              <a href={`tel:${PHONE.replace(/\s/g, "")}`} style={linkStyle}>{PHONE}</a>
            </div>
          </Section>

        </div>
      </main>

      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.06)", padding: "1.5rem", textAlign: "center" }}>
        <div style={{ fontSize: "0.8125rem", color: "rgba(255,255,255,0.25)" }}>
          © {new Date().getFullYear()} {COMPANY} · {ADDRESS} ·{" "}
          <Link href="/" style={{ color: "rgba(255,255,255,0.35)", textDecoration: "none" }}>Back to site</Link>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 style={{ fontFamily: "var(--font-barlow), sans-serif", fontSize: "1.25rem", fontWeight: 700, color: "#fff", letterSpacing: "-0.01em", marginBottom: "1rem", paddingBottom: "0.625rem", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
        {title}
      </h2>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.875rem", fontSize: "0.9375rem", lineHeight: 1.75, color: "rgba(255,255,255,0.6)" }}>
        {children}
      </div>
    </section>
  );
}

function CookieRow({ name, purpose, retention }: { name: string; purpose: string; retention: string }) {
  return (
    <tr>
      <td style={tdStyle}><span style={{ color: "#f97316", fontWeight: 600 }}>{name}</span></td>
      <td style={tdStyle}>{purpose}</td>
      <td style={tdStyle}>{retention}</td>
    </tr>
  );
}

const linkStyle: React.CSSProperties = { color: "#f97316", textDecoration: "none" };
const listStyle: React.CSSProperties = { paddingLeft: "1.25rem", display: "flex", flexDirection: "column", gap: "0.375rem" };
const tableStyle: React.CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" };
const thStyle: React.CSSProperties = { textAlign: "left", padding: "0.625rem 0.75rem", background: "rgba(255,255,255,0.04)", color: "rgba(255,255,255,0.5)", fontWeight: 600, fontSize: "0.75rem", letterSpacing: "0.06em", textTransform: "uppercase", borderBottom: "1px solid rgba(255,255,255,0.08)" };
const tdStyle: React.CSSProperties = { padding: "0.75rem", borderBottom: "1px solid rgba(255,255,255,0.05)", color: "rgba(255,255,255,0.6)", verticalAlign: "top" };
